# Generated by Django 3.0.6 on 2020-05-28 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200528_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publishDate', '-updated', '-timestamp']},
        ),
    ]
